name: Deploy React Vite App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t fe-crm-didotek .

      - name: Stop old container
        run: docker stop fe-crm-didotek-container
        continue-on-error: true

      - name: Remove old container
        run: docker rm fe-crm-didotek-container
        continue-on-error: true

      - name: Run new container
        run: docker run -d -p 8080:80 --name fe-crm-didotek-container fe-crm-didotek